src/erp各种检查/检查页面开放/Controllers/FkController.cs
using Mysoft.ModelAnalysis.Models;
using Mysoft.Utility;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using System.Web.WebSockets;
using System.Xml;
using System.Xml.Serialization;
using 检查页面开放.Business;
using 检查页面开放.Models;
using 检查页面开放.Utility;

namespace 检查页面开放.Controllers
{
    /// <summary>
    /// 分库相关检查
    /// </summary>
    public class FkController : Controller
    {
        // GET: Fk
        public ActionResult Index()
        {
            //获取所有实体
            List<MetadataEntity> entities = MetaDataOp.GetMetadataEntities();
            return View(entities);
        }

        /// <summary>
        /// 添加GUID
        /// </summary>
        public void AddBuguid()
        {
            List<MetadataEntity> entities = MetaDataOp.GetMetadataEntities();
            var errorEntity = entities.Where(t => t.IsEnableIsolateForCompany == true
            && (t.Attributes.MetadataAttributes.Any(m => string.Equals(m.Name, "buguid", StringComparison.OrdinalIgnoreCase)) == false)
            );

            foreach (var entity in errorEntity)
            {
                var fullName = entity.FullName;
                bool isXmlns = false;//xmlns:p4

                StringBuilder allTxt = new StringBuilder();
                foreach (string str in System.IO.File.ReadAllLines(fullName, Encoding.Default))
                {
                    if (isXmlns == false && str.IndexOf("xmlns:p4") > 0)
                    {
                        isXmlns = true;
                    }
                    if (string.Equals(str.Trim(), "</Attributes>", StringComparison.OrdinalIgnoreCase))
                    {
                        if (isXmlns == false)
                        {
                            allTxt.AppendLine("		<MetadataAttribute metadataStatus=\"Product\">\r\n" +
                "    		<AttributeId>" + Guid.NewGuid().ToString() + "</AttributeId>\r\n" +
                "    		<Name>BUGUID</Name>\r\n" +
                "    		<DisplayName>公司标识</DisplayName>\r\n" +
                "    		<AttributeType>Guid</AttributeType>\r\n" +
                "    		<DbType>uniqueidentifier</DbType>\r\n" +
                "    		<RequiredLevel>none</RequiredLevel>\r\n" +
                "    		<Remark />\r\n" +
                "    		<Length xsi:nil=\"true\" />\r\n" +
                "    		<IsNullable>true</IsNullable>\r\n" +
                "    		<ColumnNumber>7</ColumnNumber>\r\n" +
                "    		<IsPrimaryAttribute>false</IsPrimaryAttribute>\r\n" +
                "    		<DecimalPrecision xsi:nil=\"true\" />\r\n" +
                "    		<RelationshipId xsi:nil=\"true\" />\r\n" +
                "    		<AllowQuickFind>true</AllowQuickFind>\r\n" +
                "    		<OptionsEnum />\r\n" +
                "    		<MultiSelect>false</MultiSelect>\r\n" +
                "    		<LookupPrimaryEntityId xsi:nil=\"true\" />\r\n" +
                "    		<IsThousandth>false</IsThousandth>\r\n" +
                "    		<IsRedundance>false</IsRedundance>\r\n" +
                "    		<IsIdentity>false</IsIdentity>\r\n" +
                "    		<IsEnum>false</IsEnum>\r\n" +
                "    		<EnumInfos />\r\n" +
                "		</MetadataAttribute>");
                        }
                        else
                        {

                            allTxt.AppendLine("    <MetadataAttribute metadataStatus=\"Product\">\r\n" +
"      <AttributeId>" + Guid.NewGuid().ToString() + "</AttributeId>\r\n" +
"      <Name>BUGUID</Name>\r\n" +
"      <DisplayName>公司标识</DisplayName>\r\n" +
"      <AttributeType>Guid</AttributeType>\r\n" +
"      <DbType>uniqueidentifier</DbType>\r\n" +
"      <RequiredLevel>none</RequiredLevel>\r\n" +
"      <Remark />\r\n" +
"      <Length>0</Length>\r\n" +
"      <IsNullable>true</IsNullable>\r\n" +
"      <ColumnNumber>10</ColumnNumber>\r\n" +
"      <IsPrimaryAttribute>false</IsPrimaryAttribute>\r\n" +
"      <DecimalPrecision>0</DecimalPrecision>\r\n" +
"      <RelationshipId p4:nil=\"true\" xmlns:p4=\"http://www.w3.org/2001/XMLSchema-instance\" />\r\n" +
"      <AllowQuickFind>true</AllowQuickFind>\r\n" +
"      <OptionsEnum />\r\n" +
"      <MultiSelect>false</MultiSelect>\r\n" +
"      <LookupPrimaryEntityId p4:nil=\"true\" xmlns:p4=\"http://www.w3.org/2001/XMLSchema-instance\" />\r\n" +
"      <IsThousandth>false</IsThousandth>\r\n" +
"    </MetadataAttribute>");
                        }
                    }
                    allTxt.AppendLine(str);
                }
                FileHelper.WriteFile(fullName, allTxt.ToString());
            }
        }


        List<string> expectTable = new List<string> { "s_CwfxDcTemp", "s_FeeDcTemp", "s_Barcode", "p_CstAttribute", "s_GetInDcTemp", "YGZ_QueueChangeRecord", "s_AppProcess", "s_AppProcessDetail" };

        /// <summary>
        /// 获取分库
        /// </summary>
        /// <param name="fkSqlConn"></param>
        /// <param name="zkBuGuid">主库公司id</param>
        /// <returns></returns>
        public string CaleCount(string fkSqlConn, string zkSqlConn, Guid fkBuGuid)
        {
            //
            string fkXml = System.IO.File.ReadAllText(PathConst.Fk, Encoding.Default);
            var fkTableModel = XmlUtility.DeserializeToObject<FkTableModel>(fkXml);
            List<MetadataEntity> entities = MetaDataOp.GetMetadataEntities();
            entities.RemoveAll(t => expectTable.Contains(t.Name));

            //不分库的表在分库上查询
            List<FkResultDto> zkNfkbResultDtos = GetZkData(fkSqlConn, Guid.Empty, fkTableModel, entities.FindAll(t => t.IsEnableIsolateForCompany == false));
            //所有表在主库上查询
            List<FkResultDto> fkResultDtos = GetZkData(zkSqlConn, fkBuGuid, fkTableModel, entities);

            //分库的表在分库上查询
            List<FkResultDto> fkFk = GetZkData(fkSqlConn, fkBuGuid, fkTableModel, entities.FindAll(t => t.IsEnableIsolateForCompany == true));
            //--1、只要分库表没有数据（在分库上查询），过滤掉数据 > 0的数据 
            List<FkResultDto> fkErrorData = fkFk.FindAll(t => t.IsCal == true && t.IsFk == true && t.Count == 0);

            //--2、只要分库的表（在主库上查询），显示数据 > 0的数据
            List<FkResultDto> zkErrorData = fkResultDtos.FindAll(t => t.IsCal == true && t.IsFk == true && t.Count > 0);

            List<FkResultDto> bfkErrorData = new List<FkResultDto>();
            //--3、不分库的表，在两个库上都有数据，数据要相等
            foreach (var zk in zkNfkbResultDtos.FindAll(t => t.IsCal == true && t.IsFk == false))
            {
                var fk = fkResultDtos.First(t => t.TableName == zk.TableName);
                if (zk.Count != fk.Count)
                {
                    bfkErrorData.Add(fk);
                }
            }
            return Newtonsoft.Json.JsonConvert.SerializeObject(new FkUIResult { FkbNoData = fkErrorData, FkbZkNoData = zkErrorData, BfkbNoEqual = bfkErrorData, NoCal = fkResultDtos.FindAll(t => t.IsCal == false) });
        }

        /// <summary>
        /// 在主库中获取不分库的数据
        /// </summary>
        /// <param name="sqlConn"></param>
        /// <param name="fkTableModel"></param>
        /// <param name="entities"></param>
        /// <returns></returns>
        private static List<FkResultDto> GetZkData(string sqlConn, Guid buguid, FkTableModel fkTableModel, List<MetadataEntity> entities)
        {
            List<FkResultDto> fkResultDtos = new List<FkResultDto>();
            DataAccess dataAccess = new DataAccess(sqlConn);
            SqlParameter[] sqlParameters = new SqlParameter[] { new SqlParameter("buguid", buguid) };
            foreach (var item in entities)
            {
                FkResultDto fkResultDto = new FkResultDto();
                fkResultDto.TableName = item.Name;
                fkResultDto.IsFk = item.IsEnableIsolateForCompany;
                fkResultDto.IsCal = true;
                var fkSql = fkTableModel.CommandList.FirstOrDefault(t => t.Name.ToLower() == item.Name.ToLower());
                if (fkSql == null)
                {
                    fkResultDto.IsCal = false;
                }
                else
                {
                    fkResultDto.Count = (int)dataAccess.ExecuteScalar(fkSql.Sql, System.Data.CommandType.Text, sqlParameters);
                }
                fkResultDtos.Add(fkResultDto);
            }

            return fkResultDtos;
        }


        // 检查某个字段是否有空值
        public ActionResult CheckFieldNull()
        {
            return View();
        }

        // 检查某个字段
        public string CheckFieldAction(string sqlconn, string filed)
        {
            List<string> result = new List<string>();
            var sql = FileHelper.GetTxt(PathConst.CheckFieldAction);
            DataAccess dataAccess = new DataAccess(sqlconn);
            DataTable datatable = dataAccess.ExecuteDataset(sql, System.Data.CommandType.Text, null).Tables[0];
            foreach (DataRow row in datatable.Rows)
            {
                var tableName = row["name"].ToString();
                string searchSql = $"SELECT COUNT(1) FROM {tableName} WHERE {filed} IS NULL";
                int count = (int)dataAccess.ExecuteScalar(searchSql, System.Data.CommandType.Text, null);
                if (count > 0)
                {
                    result.Add(tableName);
                }
            }
            return result.ToJson();
        }
    }

}

src/erp各种检查/检查页面开放/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

src/erp各种检查/检查页面开放/Views/Home/CheckV3Model.cshtml
@model List<Result>

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
    List<Result> result = Model as List<Result>;
}

@{
    foreach (var r in result)
    {
        <div>@r.Content</div>
    }
}

src/erp各种检查/检查页面开放/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

src/erp各种检查/检查页面开放/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

src/erp各种检查/检查页面开放/Views/Home/IndexList.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<style>
    #divAccord span {
        cursor: pointer;
    }

    #divAccord p {
        padding-left: 5px;
    }
</style>
<html>
<head>
    <title>各种问题扫描</title>
    <meta charset="UTF-8">
    <title>Full Layout - jQuery EasyUI Demo</title>
    <link rel="stylesheet" type="text/css" href="~/Scripts/jquery-easyui-1.7.0/themes/bootstrap/easyui.css">
    <link rel="stylesheet" type="text/css" href="~/Scripts/jquery-easyui-1.7.0/themes/icon.css">
    <script type="text/javascript" src="~/Scripts/jquery-easyui-1.7.0/jquery.min.js"></script>
    <script type="text/javascript" src="~/Scripts/jquery-easyui-1.7.0/jquery.easyui.min.js"></script>
</head>
<body class="easyui-layout">
    <div data-options="region:'west',split:false,title:''" style="width: 250px; padding: 0; ">
        <div id="divAccord" class="easyui-accordion" style="width: 100%; ">
            <div title="迭代过程" data-options="" style="overflow: auto; ">
                <p>
                    <span href="@Url.Action("InterfaceMethod","GetAppApi")" menua="true">检查Interface接口</span>
                </p>
                <p>
                    <span href="@Url.Action("Index","GetAppApi")" menua="true">检查App接口（包括内部、外部）</span>
                </p>
                <p>
                    <span href="@Url.Action("MethodLog","GetAppApi")" menua="true">接口对比</span> 
                </p>
                <p>
                    <span href="@Url.Action("InterfaceRemark","GetAppApi")" menua="true">接口参数说明</span> 
                    
                </p>
                <p>
                    <span href="@Url.Action("YunCeIndex","GetAppApi")" menua="true">云测接口覆盖</span>
                </p>
            </div>

            <div title="发版前检查" data-options="" style="overflow: auto;">

                <p>
                    <span href="@Url.Content("ViewCheckNoUserXMLCommand")" menua="true">检查无用的XMLCommand</span>
                </p>
                <p>
                    <span href="@Url.Action("Index","CheckLange")" menua="true">多语言未翻译</span>
                </p>
                <p>
                    <span href="@Url.Action("Index","Fk")" menua="true">分库检查</span>
                </p>
                <p>
                    <span href="@Url.Action("Index","Dsq")" menua="true">多时区未处理</span>
                </p>
                <p>
                    <span href="@Url.Action("Index","GetRepeatMethod")" menua="true">方法名重复</span>
                </p>
                <p>
                    <span href="@Url.Action("NoVirtualMethod","GetRepeatMethod")" menua="true">不为虚方法</span>
                </p>
                <p>
                    <span href="@Url.Action("Index","CheckLan")" menua="true">多语言重复检查</span>
                </p>
                <p>
                    <span href="@Url.Action("Index","CheckOhterMetadata")" menua="true">是否包含其他系统元数据</span>
                </p>

                <p>
                    <span href="@Url.Action("GetMate","GetModelMate")" menua="true">检查插件包元数据</span>
                </p>

            </div>

            <div title="其他检查" data-options="" style="overflow: auto;">

                <p>
                    <span href="@Url.Content("ViewKf")" menua="true">页面开放</span>
                </p>
                <p>
                    <span href="@Url.Content("ViewQdAppService")" menua="true">Appservice调用检查</span>
                </p>


                <p>
                    <span href="@Url.Content("ViewCheckAppMethodIsUse")" menua="true">检查Appservice是否调用</span>
                </p>
                <p>
                    <span href="@Url.Content("ViewCheckNoUserFile")" menua="true">检查js、>检查js、aspx是否还有用</span>
                </p>
                <p>
                    <span href="@Url.Content("ViewGetFormNqWg")" menua="true">获取表单上的内嵌网格设置了查询权限</span>
                </p>
                <p>
                    <span href="@Url.Content("ViewQdAppService")" menua="true">检查 appservice是否夸模块调用</span>
                </p>
                <p>
                    <span href="@Url.Action("ComperResult", "MetadataComper")" menua="true">检查 实体与元数据中不一致问题</span>
                </p>
                <p>
                    <span href="@Url.Action("CheckFieldNull","Fk")" menua="true">字段为空检查（BUGUID）</span>
                </p>

            </div>
        </div>
    </div>
    <div data-options="region:'center',title:''">
        <div id="easyuiTabs" class="easyui-tabs" data-options="tools:'#tab-tools'" style="width: 100%; height: 100%;">
        </div>
    </div>
</body>

</html>
<script>
    var $easyuiTabs = $("#easyuiTabs");
    function addPanel(title, src) {
        $easyuiTabs.tabs('add', {
            title: title,
            content: '<iframe src="' + src + '"  width="100%" height="100%" ></iframe>',
            pill: true,
            closable: true,
            tools: [{
                iconCls: 'icon-mini-refresh',
                handler: function () {
                    var tab = $easyuiTabs.tabs('getSelected');
                    $easyuiTabs.tabs('update', {
                        tab: tab,
                        options: {
                            //title: 'new title',
                            //iconCls: 'icon-save'
                        }
                    });
                }
            }]
        });
    }

    $(document).ready(function () {
        $("#divAccord").find("span[menua='true']").click(function () {
            var $this = $(this);
            var text = $this.html();
            var e = $easyuiTabs.tabs('exists', text);
            if (e == true) {
                $easyuiTabs.tabs('select', text);
                return;
            }
            var href = $this.attr("href");
            addPanel(text, href);
        });
    });
</script>

src/erp各种检查/检查页面开放/Views/Home/ViewCheckAppMethodIsUse.cshtml
@model List<String>

@{
    Layout = null;
    List<String> noUseList = Model;
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<!DOCTYPE html>


<div>
    <div>未使用的AppService方法 <span id="allZk">全部展开</span></div>
    <div id="contentDiv" style="height: 200px;overflow: scroll">
        @foreach (string noUse in noUseList)
        {
            <div>@noUse</div>
        }
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#allZk").click(function() {
            $("#contentDiv").css("height","100%");
        });
    })

</script>

src/erp各种检查/检查页面开放/Views/Home/ViewCheckNoUserFile.cshtml
@using 检查页面开放.Models
@model dynamic

<script src="~/Scripts/jquery-1.10.2.js"></script>
@{
    ViewBag.Title = "检查js、aspx是否还有用";
    Layout = null;
    var checkNoUserFileModel = Model as CheckNoUserFileModel;
    DateTime start = ViewBag.Start;
    DateTime end = ViewBag.End;
}

<div>
    检查js、aspx是否未使用数量(js:@checkNoUserFileModel.AllJsName.Count(t => t.PpCount == 0) aspx:@checkNoUserFileModel.AllAspxName.Count(t => t.PpCount == 0)) <a href="#" onclick="showInfoDiv()">展示</a>
</div>
<div>开始：@start.ToString() 结束：@end.ToString()</div>
<div id="InfoDiv">
    <div>js未使用</div>
    @{
        foreach (JsClass jsClass in checkNoUserFileModel.AllJsName.Where(t => t.PpCount == 0))
        {
            <div>@jsClass.Name</div>
        }
    }
    <div>aspx未使用</div>
    @{
        foreach (AspxClass aspxClass in checkNoUserFileModel.AllAspxName.Where(t => t.PpCount == 0))
        {
            <div>@aspxClass.Name</div>
        }
    }
</div>
<script>
    $(document).ready(function () {

    });
    function showInfoDiv() {
        $("#InfoDiv").toggle();
    }
</script>

src/erp各种检查/检查页面开放/Views/Home/ViewCheckNoUserXMLCommand.cshtml
@model dynamic

@{
    ViewBag.Title = "检查无用的xmlcommand";
    Layout = null;
    List<String> noUserXmlCommand = Model as List<String>;
}

@{
    foreach (string key in noUserXmlCommand)
    {
        <div>@key</div>
    }}

src/erp各种检查/检查页面开放/Views/Home/ViewComboBoxNoSetText.cshtml
@model List<String>

@{
    Layout = null;
    List<String> noUseList = Model;
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<!DOCTYPE html>


<div>
    <div>检查元数据中comboBox 没有设置文本 <span id="allZk">全部展开</span></div>
    <div id="contentDiv" style="height: 200px;overflow: scroll">
        @foreach (string noUse in noUseList)
        {
            <div>@noUse</div>
        }
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#allZk").click(function() {
            $("#contentDiv").css("height","100%");
        });
    })

</script>

src/erp各种检查/检查页面开放/Views/Home/ViewFile.cshtml
@model List<String>

@{
    List<string> list = Model as List<string>;
}

<h2>title</h2>
@foreach (string s in list)
{
    <p>@s</p>
}

src/erp各种检查/检查页面开放/Views/Home/ViewGetFormNqWg.cshtml
@{
    ViewBag.Title = "title";
    Layout = null;
    Dictionary<string, string> wentiGrid = Model as Dictionary<string, string>;
}

<h2>title</h2>
<table>
    @{foreach (KeyValuePair
                    <string, string>
                        s in wentiGrid)
        {
            <tr>
                <td>@s.Key</td>
                <td>@s.Value</td>
            </tr>
        }
    }
</table>

src/erp各种检查/检查页面开放/Views/Home/ViewKf.cshtml
@using 检查页面开放.Models
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = null;
    YmModel ymModel = Model as YmModel;
}
<script src="~/Scripts/jquery-1.10.2.js"></script>

<div>总数 @ymModel.TotalCount</div>
<div>全开放 @ymModel.QkfCount</div>
<div>部分开放 @ymModel.BfCount</div>
<div>不开放 @ymModel.BkfCount <a href="#" onclick="showBkfDiv()">展示</a></div>
<div id="BkfDiv" style="display: none; border: aquamarine 1px solid;">
    @foreach (string m in ymModel.PtBkfList)
    {
        <div>@m</div>
    }
</div>
<div>ASPX页面 @ymModel.AspxCount <a href="#" onclick="showAspxDiv()">展示</a></div>
<div id="AspxDiv" style="display: none; border: aquamarine 1px solid;">
    @foreach (var m in ymModel.ApsxBkfList)
    {
        <div>@m</div>
    }
</div>
<div>开放比例 @(ymModel.QkfCount * 0.01 / (ymModel.TotalCount) * 100 * 100)</div>
<script>
    $(document).ready(function () {

    });
    function showBkfDiv() {
        $("#BkfDiv").toggle();
    }

    function showAspxDiv() {
        $("#AspxDiv").toggle();
    }
</script>

src/erp各种检查/检查页面开放/Views/Home/ViewPrivateAppMethodIsUse.cshtml
@model List<String>

@{
    Layout = null;
    List<String> noUseList = Model;
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<!DOCTYPE html>


<div>
    <div>private方法 <span id="allZk">全部展开</span></div>
    <div id="contentDiv" style="height: 200px;overflow: scroll">
        @foreach (string noUse in noUseList)
        {
            <div>@noUse</div>
        }
    </div>
</div>
<script>
    $(document).ready(function() {
        $("#allZk").click(function() {
            $("#contentDiv").css("height","100%");
        });
    })

</script>

src/erp各种检查/检查页面开放/Views/Home/ViewQdAppService.cshtml
@using 检查页面开放.Models
@model QdAppserService
@*Appservice调用检查*@
@{
    ViewBag.Title = "title";
    Layout = null;
    QdAppserService adAppserService = Model as QdAppserService;
}

<h2>title</h2>
<div style="font-size: 14px; font:bold; ">js中调用了多个Appservice</div>
@{
    for (int i = 0; i < adAppserService.DgAppserviceList.Count; i++)
    {
        <div>@adAppserService.DgAppserviceList[i]</div>
    }
}

<div style="font-size: 14px; font: bold;">js中直接调用ajax</div>
@{
    for (int i = 0; i < adAppserService.JsAjaxList.Count; i++)
    {
        <div>@adAppserService.JsAjaxList[i]</div>
    }
}
<div style="font-size: 14px; font: bold;">js中不包含code  </div>
@{
    for (int i = 0; i < adAppserService.NoContaintMcode.Count; i++)
    {
        <div>@adAppserService.NoContaintMcode[i]</div>
    }
}

<div style="font-size: 14px; font: bold;">js与AppService的code不一致  </div>
@{
    for (int i = 0; i < adAppserService.CodeNoMatch.Count; i++)
    {
        <div>@adAppserService.CodeNoMatch[i]</div>
    }
}