src/erp各种检查/检查页面开放/Models/MethodLog.cs
using EasyFramework.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace 检查页面开放.Models
{
    [TableAttribute("MethodLog")]
    public class MethodLog
    {
        [Column("Name")]
        public string Name { get; set; }

        [Column("Data")]
        public string Data { get; set; }

        [Column("CreateTime")]
        public DateTime CreateTime { get; set; }

        [Column("ID", ColumnType.IdentityAndPrimaryKey)]
        public int ID { get; set; }
    }
}

src/erp各种检查/检查页面开放/Controllers/GetAppApiController.cs
using Mysoft.ModelAnalysis.Utility;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Mysoft.Utility;
using 检查页面开放.Business;
using 检查页面开放.Models;
using System.Globalization;
using MdDocGenerator.Util;
using MdDocGenerator;
using System.Net.Mime;
using System.Text;
using System.Threading;

namespace 检查页面开放.Controllers
{
    /// <summary>
    /// 获取App对外开放的接口
    /// </summary>
    public class GetAppApiController : Controller
    {
        GetAppApi getAppApi = new GetAppApi();
        MethodLogBusiness methodLogBusiness = new MethodLogBusiness();
        YunCeBusiness yunCeBusiness = new YunCeBusiness();
        YunCeForSjzx yunCeForSjzx = new YunCeForSjzx();

        /// <summary>
        /// interface、appservice方法展示页面
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            getAppApi.GetApi();
            getAppApi.GetInterFaceApi();
            return View(getAppApi.List);
        }

        //public ActionResult InterfaceMethod()
        //{
        //    getAppApi.GetInterFaceApi();
        //    return View(getAppApi.List);
        //}

        #region 接口日志
        /// <summary>
        /// 接口日志页面
        /// </summary>
        /// <returns></returns>
        public ActionResult MethodLog()
        {
            //getAppApi.GetApi();
            ViewBag.MethodLogList = methodLogBusiness.Query();
            return View();
        }

        /// <summary>
        /// 记录
        /// </summary>
        /// <param name="logName"></param>
        public void JiLu(string logName)
        {
            if (string.IsNullOrEmpty(logName))
            {
                throw new BusinessLogicException("名称不能为空！");
            }
            if (methodLogBusiness.IsExiste(logName))
            {
                throw new BusinessLogicException("名称重复！");
            }

            List<AppDataSource> appDataSource = DataSourceHelp.GetModelDlls(System.Web.HttpContext.Current.Server.MapPath(PathConst.AppDataSouce));
            methodLogBusiness.Add(new Models.MethodLog
            {
                Name = logName,
                Data = Newtonsoft.Json.JsonConvert.SerializeObject(getAppApi.GetModels(appDataSource)),
                CreateTime = DateTime.Now
            });

        }

        /// <summary>
        /// 比较
        /// </summary>
        /// <param name="oldLog"></param>
        /// <param name="newLog"></param>
        /// <returns></returns>
        public string Compare(int oldLog, int newLog)
        {
            var log1 = methodLogBusiness.Get(oldLog);
            var log2 = methodLogBusiness.Get(newLog);
            var modelList1 = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Model>>(log1.Data);
            var modelList2 = Newtonsoft.Json.JsonConvert.DeserializeObject<List<Model>>(log2.Data);

            List<ModelDiff> modelDiffs = new List<ModelDiff>();
            foreach (var model1 in modelList1)
            {
                var model2 = modelList2.FirstOrDefault(t => t.Name == model1.Name);
                //如果为空，默认一个值
                if (model2 == null)
                {
                    model2 = new Model
                    {
                        Name = "",
                        MethodList = new List<MethodInfo>()
                    };
                }
                modelDiffs.Add(new ModelDiff
                {
                    Model = model1,
                    MethodDiffs = GetAppApi.CompareDll(model1.MethodList, model2.MethodList)
                });
            }
            return Newtonsoft.Json.JsonConvert.SerializeObject(modelDiffs);
        }

        #endregion

        #region 云测接口完成情况

        /// <summary>
        /// 云测接口情况页面
        /// </summary>
        /// <returns></returns>
        public ActionResult YunCeIndex()
        {
            List<AllAppDataSource> allAppDataSources = DataSourceHelp.GetAllModelDlls(System.Web.HttpContext.Current.Server.MapPath(PathConst.AllAppDataSouce));
            ViewBag.AllAppDataSources = allAppDataSources;
            return View();
        }

        /// <summary>
        /// 获取系统接口结果
        /// </summary>
        /// <param name="modelCode"></param>
        /// <returns></returns>
        public string GetYc(string modelCode)
        {
            YcResult ycResult = GetYcRe(modelCode);

            return ycResult.ToJson();
        }

        /// <summary>
        /// 获取云测结果
        /// </summary>
        /// <param name="modelCode"></param>
        /// <returns></returns>
        private YcResult GetYcRe(string modelCode)
        {
            List<AllAppDataSource> allAppDataSources = DataSourceHelp.GetAllModelDlls(System.Web.HttpContext.Current.Server.MapPath(PathConst.AllAppDataSouce));
            var app = allAppDataSources.FirstOrDefault(t => t.Code == modelCode);
            if (app == null)
            {
                throw new Exception("请配置系统");
            }
            List<Model> models = yunCeBusiness.Search(app.Ycurl, app.AppDataSources);
            List<MethodInfo> allMethod = new List<MethodInfo>();
            foreach (var model in models)
            {
                allMethod.AddRange(model.MethodList);

            }
            List<InterFaceResult> interFaceResults = new List<InterFaceResult>();
            var zt = new InterFaceResult
            {
                Remark = "整体",
                Count = allMethod.Count,
                YcCount = allMethod.Count(t => t.YCIsCover == true),
                MethodList = allMethod
            };
            zt.Fgl = zt.YcCount * 1.00 / zt.Count * 100;
            interFaceResults.Add(zt);

            var dsf = new InterFaceResult
            {
                Remark = "外部第三方调用接口",
                Count = allMethod.Count(t => t.IsOpen == true),
                YcCount = allMethod.Count(t => t.IsOpen == true && t.YCIsCover == true),
                MethodList = allMethod.FindAll(t => t.IsOpen == true)
            };
            dsf.Fgl = dsf.YcCount * 1.00 / dsf.Count * 100;
            interFaceResults.Add(dsf);

            var kzxt = new InterFaceResult
            {
                Remark = "跨子系统及业务单元调用接口",
                Count = allMethod.Count(t => t.IsOpen.GetValueOrDefault() == false && t.IsPublic == true),
                YcCount = allMethod.Count(t => t.IsOpen.GetValueOrDefault() == false && t.IsPublic == true && t.YCIsCover == true),
                MethodList = allMethod.FindAll(t => t.IsOpen.GetValueOrDefault() == false && t.IsPublic == true)
            };
            kzxt.Fgl = kzxt.YcCount * 1.00 / kzxt.Count * 100;
            interFaceResults.Add(kzxt);

            var nbjk = new InterFaceResult
            {
                Remark = "业务单元内部接口",
                Count = allMethod.Count(t => t.IsPublic.GetValueOrDefault() == false),
                YcCount = allMethod.Count(t => t.IsPublic.GetValueOrDefault() == false && t.YCIsCover == true),
                MethodList = allMethod.FindAll(t => t.IsPublic.GetValueOrDefault() == false)
            };
            nbjk.Fgl = nbjk.YcCount * 1.00 / nbjk.Count * 100;
            interFaceResults.Add(nbjk);

            YcResult ycResult = new YcResult();
            ycResult.InterFaceResults = interFaceResults;
            ycResult.Models = models;
            return ycResult;
        }

        /// <summary>
        /// 获取系统接口结果-给云测平台用的
        /// </summary>
        /// <param name="modelCode"></param>
        /// <returns></returns> 
        public string GetYcForYcPt(string modelCode)
        {
            if (string.Equals(modelCode, "SJZX", StringComparison.OrdinalIgnoreCase))
            {
                return yunCeForSjzx.Search();
            }
            YcResult re = GetYcRe(modelCode);
            re.Models = null;
            return re.ToJson();
        }

        #endregion

        #region 接口参数说明
        public ActionResult InterfaceRemark()
        {
            getAppApi.GetApi();
            getAppApi.GetInterFaceApi();
            return View(getAppApi.List);
        }

        public void RefreshMd() {
            var files = Directory.GetFiles(PathConst.BinPath, ConfigHelper.Dll, SearchOption.AllDirectories)
               .ToList();
            new MarkdownGenerator().Generate(files, PathConst.MdFile);

        }

        public ActionResult ViewRemark(string name)
        {
            var content = FileHelper.GetTxt(name, Encoding.UTF8);
            ViewBag.MdContent = content;
            return View();
        }
        #endregion
    }

    public class YcResult
    {
        public List<InterFaceResult> InterFaceResults { get; set; }

        public List<Model> Models { get; set; }
    }

    public class InterFaceResult
    {
        public string Remark { get; set; }

        /// <summary>
        /// 接口数量
        /// </summary>
        public int Count { get; set; }

        /// <summary>
        /// 云测覆盖数量
        /// </summary>
        public int YcCount { get; set; }
        /// <summary>
        /// 覆盖率
        /// </summary>
        public double Fgl { get; set; }

        /// <summary>
        /// 所有方法
        /// </summary>
        public List<MethodInfo> MethodList { get; set; }
    }

}

src/erp各种检查/检查页面开放/Views/GetAppApi/Index.cshtml
@model List<检查页面开放.Models.MethodInfo>

@{
    ViewBag.Title = "title";
    Layout = null;
    var methodList = Model as List<检查页面开放.Models.MethodInfo>;
}

<script src="~/Scripts/jquery-1.10.2.js"></script>
@{
    var groupList = methodList.GroupBy(t => t.ClassName);
    var classCount = 1;
    <span>总计：@methodList.Count</span>
    foreach (var group in groupList)
    {
        <div style="border: solid 1px #000000; margin-top: 10px;">
            <div style="font-weight: bold; cursor: pointer;" onclick="showBkfDiv(this)">@(classCount++)类名称：@group.Key<span>展开/折叠</span></div>
            <div style=" display: none;">
                @{
                    var a = 1;
                    foreach (var collection in group)
                    {
                        <div style="border: 1px solid #000000"><span>@(a++)、</span>@collection.MethodName</div>
                    }
                }
            </div>
        </div>
    }
}
<script>
    function showBkfDiv(obj) {
        $(obj).next().toggle();
    }

</script>

src/erp各种检查/检查页面开放/Views/GetAppApi/InterfaceMethod.cshtml
@model List<检查页面开放.Business.App>

@{
    ViewBag.Title = "title";
    Layout = null;
    var appList = Model as List<检查页面开放.Business.App>;
}

<script src="~/Scripts/jquery-1.10.2.js"></script>
@{
    var dllGroup = appList.GroupBy(t => t.DllName);
    <span>总计：@appList.Count</span>
    foreach (var dllG in dllGroup)
    {
        <div style="font-size: 20px; font-weight: bold;">dll名称： @dllG.Key</div>
        var groupList = dllG.GroupBy(t => t.ClassName);
        var classCount = 1;
        foreach (var group in groupList)
        {
            <div style="border: solid 1px #000000; margin-top: 10px;">
                <div style="font-weight: bold; cursor: pointer;" onclick="showBkfDiv(this)">@(classCount++)类名称：@group.Key<span>展开/折叠</span></div>
                <div style=" display: none;">
                    @{
                        var a = 1;
                        foreach (var collection in group)
                        {
                            <div style="border: 1px solid #000000"><span>@(a++)、</span>@collection.MethodName</div>
                        }
                    }
                </div>
            </div>
        }
    }
   
}
<script>
    function showBkfDiv(obj) {
        $(obj).next().toggle();
    }

</script>

src/erp各种检查/检查页面开放/Views/GetAppApi/InterfaceRemark.cshtml
@model List<检查页面开放.Models.MethodInfo>

@{
    ViewBag.Title = "title";
    Layout = null;
    var methodList = Model as List<检查页面开放.Models.MethodInfo>;
}

<script src="~/Scripts/jquery-1.10.2.js"></script>
<div>
    <button onclick="refreshMd(this)">刷新文档</button>
</div>
@{
    var groupList = methodList.GroupBy(t => t.ClassName);
    var classCount = 1;
    <span>总计：@methodList.Count</span>
    foreach (var group in groupList)
    {
        <div style="border: solid 1px #000000; margin-top: 10px;">
            <div style="font-weight: bold; cursor: pointer;" onclick="showBkfDiv(this)">@(classCount++)类名称：@group.Key<span>展开/折叠</span></div>
            <div style=" display: none;">
                @{
                    var a = 1;
                    foreach (var collection in group)
                    {
                        <div style="border: 1px solid #000000"><span>@(a++)、</span>@collection.MethodName <a href="javascript:void(0);" onclick="viewRemark(this)" mkUrl='@Path.Combine("Md",@group.Key,@group.Key+"_"+@collection.MethodName+".md")'>说明</a></div>
                    }
                }
            </div>
        </div>
    }
}
<script>

    function showBkfDiv(obj) {
        $(obj).next().toggle();
    }
    function viewRemark(obj) {
        var name = $(obj).attr("mkUrl");
        var url = "@Url.Action("ViewRemark", "GetAppApi")?name=" +name;
        window.open(url);
    }

    function refreshMd(obj) {
        var $obj = $(obj);
        $obj.attr("disabled", "disabled");
        $.ajax({
            url: "@Url.Action("RefreshMd", "GetAppApi")",
            success: function () {
                alert("更新成功！");
            },
            error: function() {
                alert("更新失败！");
            },
            complete: function () {
                $obj.removeAttr("disabled");
            }
        });
    }

</script>

src/erp各种检查/检查页面开放/Views/GetAppApi/MethodLog.cshtml
@using 检查页面开放.Models
@{
    ViewBag.Title = "MethodLog";
    Layout = null;
    List<MethodLog> methodLogList = ViewBag.MethodLogList;
    var json = Newtonsoft.Json.JsonConvert.SerializeObject(methodLogList);
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/vue.js"></script>
<style>
    select {
        min-width: 100px;
    }

    table {
        border-collapse: collapse;
        border: 1px solid black;
    }

    th, td {
        border: 1px solid black;
    }
	.spanModel{
		font:bold;
        padding-left:20px;
	}
    body{
        font-size:14px; 
    }
</style>
<div id="MethodVue">
    <div>
        迭代名称： 
        <input id="LogNameText" />
        <button onclick="jiLu(this)">记录</button>
    </div>
    <div>
        对比：
        <select id="Compare1">
            <option v-for="c in Compares" :value="c.ID">
                {{ c.Name }}
            </option>
        </select>
        <select id="Compare2">
            <option v-for="c in Compares" :value="c.ID">
                {{ c.Name }}
            </option>
        </select>
        <button onclick="compare(this)">对比</button>
        <div>
            <span>结果：</span>
            <div v-for="md in ModelDiffs">
                <div>
                    <span style="cursor:pointer;" onclick="modelDisplay(this)">折叠/展开</span> <span class='spanModel'>模块:{{md.Model.Name}}</span>
					<div style="display:none;">
                    <table>
                        <thead><tr> <th>C1:类.方法</th> <th>C2:类.方法</th><th>备注</th></tr></thead>
                        <tbody>
                            <tr v-for="d in md.MethodDiffs">
                                <td>{{d.Method1.ClassName}}.{{d.Method1.MethodName}}</td>
                                <td>{{d.Method2.ClassName}}.{{d.Method2.MethodName}}</td>
                                <td v-if="d.DiffType==1">删除</td>
                                <td v-if="d.DiffType==2">参数调整</td>
								<td v-if="d.DiffType==4">注释调整</td>
                                <td v-if="d.DiffType==5">新增</td>
                            </tr>
                        </tbody>
                    </table>
					</div>
                </div>
            </div>
            
        </div>
    </div>
</div>

<script>
    var compares = eval(@Html.Raw(json));
   var vueData= new Vue({
        el: '#MethodVue',
        data: {
            Compares: compares,
            ModelDiffs:[]
        }
    });

    function jiLu(obj) {
        $.ajax({
            url: "@Url.Content("JiLu")",
            data: "logName=" + $("#LogNameText").val(),
            success: function () {
                alert("记录成功！");
            },
            error: function (a, b, c) {
                alert(a.responseText);
            }
        }).always(function(a,b,c){
		 
		});
    }

    function compare() {
        var c1 = $("#Compare1").val();
        var c2=$("#Compare2").val();

        $.ajax({
            url: "@Url.Content("Compare")",
            data: "oldLog=" + c1 + "&newLog=" + c2,
            dataType:"json",
            success: function (re) {
                vueData.ModelDiffs = re;
            },
            error: function (a, b, c) {
                alert(a.responseText);
            }
        });
    }

	function modelDisplay(obj){
		var $this=$(obj);
		$this.nextAll("div").toggle();
	}
</script>

src/erp各种检查/检查页面开放/Views/GetAppApi/ViewRemark.cshtml
@{
    ViewBag.Title = "接口说明";
    Layout = null;
}
<script type="text/javascript" src="~/Scripts/jquery-easyui-1.7.0/jquery.min.js"></script>
<script src="~/Scripts/showdown-master/dist/showdown.min.js"></script>
<style>
   /* <--引用样式--! >
    blockquote {
        border-left: #eee solid 5px;
        padding-left: 20px;
    }

    <--列表样式--! >
    ul li {
        line-height: 20px;
    }

    <--代码样式--! >
    code {
        color: #D34B62;
        background: #F6F6F6;
    }*/
    
</style>
<div id="result"></div>
<textarea id="md" >@ViewBag.MdContent</textarea> 
<script>
    //方法一：
    //获取url中的参数
    function getUrlParam(name) {
        var reg = new RegExp("(^|&)" + name + "=([^&]*)(&|$)"); //构造一个含有目标参数的正则表达式对象
        var r = window.location.search.substr(1).match(reg);  //匹配目标参数
        if (r != null) return unescape(r[2]); return null; //返回参数值
    }

    var text = $("#md").val(); 
    //创建实例
    var converter = new showdown.Converter();
    //进行转换
    var html = converter.makeHtml(text);
    //展示到对应的地方  result便是id名称
    document.getElementById("result").innerHTML = html;


    //var url = decodeURI(decodeURI(getUrlParam("name")));
    //url = "D:\\gitee\\自写工具\\src\\erp各种检查\\检查页面开放\\Md\\EAgreementAppService\\EAgreementAppService_GetZfEAgreementPrintSet.md";
    //$.get(url, function (text) {
    //    debugger
    //    //创建实例
    //    var converter = new showdown.Converter();
    //    //进行转换
    //    var html = converter.makeHtml(text);
    //    //展示到对应的地方  result便是id名称
    //    document.getElementById("result").innerHTML = html;
    //});


</script>

src/erp各种检查/检查页面开放/Views/GetAppApi/YunCeIndex.cshtml
@model  List<检查页面开放.Models.Model>
@using Mysoft.Utility;
@using 检查页面开放.Models

@{
    ViewBag.Title = "YunCeIndex";
    List<AllAppDataSource> allAppDataSources = ViewBag.AllAppDataSources;

    Layout = null;
}
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/vue.js"></script>
<style>
    select {
        min-width: 100px;
    }

    table {
        border-collapse: collapse;
        border: 1px solid black;
    }

    th, td {
        border: 1px solid black;
    }

    .spanModel {
        font: bold;
        padding-left: 20px;
    }

    body {
        font-size: 14px;
    }

    .green {
        background-color: green;
    }

    .red {
        background-color: palevioletred;
    }
</style>
<div>
    <div>
        系统：<select id="opApp" style="width: 300px;">
            <option value=""></option>
            @{
                foreach (var app in allAppDataSources)
                {

                    <option value="@app.Code">@app.Name</option>
                }
            }
        </select>
        <button onclick="check(this)">检查</button>
    </div>
</div>

<div id="MethodVue">
    <h3>整体</h3>
    <table>
        <thead><tr><td>说明</td><td>接口数</td><td>覆盖个数</td><td>覆盖率</td></tr></thead>
        <tbody>
            <tr v-for="md in InterFaceResults">
                <td>{{md.Remark}}</td>
                <td>{{md.Count}}</td>
                <td>{{md.YcCount}}</td>
                <td>{{md.Fgl}}</td>
                
                <td>
                    <span style="cursor:pointer;" v-on:click="modelDisplay($event)" ref="disSpan">折叠/展开</span>
                    <div style="display:none;">
                        <table>
                            <thead><tr> <th>类.方法</th> <th>是否覆盖</th> <th>是否对外</th> </tr></thead>
                            <tbody>
                                <tr v-for="d in md.MethodList" v-bind:class="{green:d.YCIsCover,red:d.YCIsCover!=true}">
                                    <td>{{d.ClassFullName}}.{{d.MethodName}}</td>
                                    <td v-if="d.YCIsCover==true">已覆盖</td>
                                    <td v-if="d.YCIsCover!=true">未覆盖</td>
                                    <td v-if="d.IsOpen==true">对外</td>
                                    <td v-if="d.IsOpen!=true">对内</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </td>
                
            </tr>
        </tbody>
    </table>


    <h3>按模块</h3>
    <div>
        <div v-for="md in Models">
            <div>
                <span style="cursor:pointer;" v-on:click="modelDisplay($event)" ref="disSpan">折叠/展开</span>
                <span class='spanModel'>
                    模块:{{md.Name}}
                    总数:{{  Object.keys(md.MethodList).length}}
                    已覆盖:{{ coverCount(md) }}
                    未覆盖:{{ noCoverCount(md)}}
                </span>
                <div style="display:none;">
                    <table>
                        <thead><tr> <th>类.方法</th> <th>是否覆盖</th> <th>是否对外</th> </tr></thead>
                        <tbody>
                            <tr v-for="d in md.MethodList" v-bind:class="{green:d.YCIsCover,red:d.YCIsCover!=true}">
                                <td>{{d.ClassFullName}}.{{d.MethodName}}</td>
                                <td v-if="d.YCIsCover==true">已覆盖</td>
                                <td v-if="d.YCIsCover!=true">未覆盖</td>
                                <td v-if="d.IsOpen==true">对外</td>
                                <td v-if="d.IsOpen!=true">对内</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>
<script>

   var vueData = new Vue({
       el: '#MethodVue',
       data: {
           Models: [],
           InterFaceResults:[]
       },
       computed: {
       },
       methods: {
           modelDisplay: function(e) {
               var $this = $(e.currentTarget);
               $this.nextAll("div").toggle();
           },
           coverCount: function(md) {
               var count = 0;
               for (var i = 0; i < md.MethodList.length; i++) {
                   if (md.MethodList[i].YCIsCover == true) {
                       count++;
                   }
               }
               return count;
           },
           noCoverCount: function(md) {
               var count = 0;
               for (var i = 0; i < md.MethodList.length; i++) {
                   if (md.MethodList[i].YCIsCover != true) {
                       count++;
                   }
               }
               return count;
           }
       }
   });

   function check(obj) {
       var selOpp = $("#opApp option:selected");
       var selCode = selOpp.val();
       if (selCode == "") {
           alert("请选择系统！");
           return;
       }
       var $obj = $(obj);
       $obj.attr("disabled", "disabled");
       $.ajax({
           url: '@Url.Content("GetYc")',
           data: "modelCode=" + selCode ,
           dataType:"json",
           success: function (re) {
               vueData.Models = re.Models;
               vueData.InterFaceResults = re.InterFaceResults;
           },
           error: function (a, b, c) {
               alert(a.responseText);
           },
           complete:function() {
               $obj.removeAttr("disabled");
           }
       });
   }
</script>